### ISSUE TITLE
Issues with the table alias

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-DC_Multilingual#42]
Internally the dc multilingual (v3) models uses aliases for the table references. This leads to issues when calling some finders which does not set the alias, f.e. `findMultipleByIds`. It leads to following error because the table name cannot be used in the where clause anymore.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_sgc_property.id' in 'where clause'
```

**Comment by Toflar** [comment]
I cannot work on this project at all atm so if you need that bugfix, please help me out here.

**Comment by dmolineus** [comment]
Atm I use a workaround by replacing `tl_table_name.` with `t1.` in the `find` method. Not sure if this would be robust enough for a general fix. If this fix is fine with you, I'll provide a PR for it.

**Comment by Toflar** [comment]
ping @terminal42/pilots

**Comment by aschempp** [comment]
I've had similar issues in Isotope, which was the original idea for DC_Multilingual. I think I changed the implementation to use the actual table name as the prefix for the base table. Imho that could be a bugfix because noone is supposed to know how the table aliases are used atm.

@dmolineus maybe you can provide a pull request?

**Comment by dmolineus** [comment]
Here we go #43.
